export { default as DropdownIcon } from '../src/Assets/Icon/dropdown.svg';
export { default as ViewIcon } from '../src/Assets/Icon/view.svg';
export { default as DeleteIcon } from '../src/Assets/Icon/delete.svg';
export { default as CrossIcon } from '../src/Assets/Icon/cross.svg';
export { default as CalenderIcon } from '../src/Assets/Icon/calender.svg';
export { default as SearchIcon } from '../src/Assets/Icon/search.svg';
export { default as LocationIcon } from '../src/Assets/Icon/location.svg';
export { default as HomeIcon } from '../src/Assets/Icon/home.svg';
export { default as NotificationIcon } from '../src/Assets/Icon/notification.svg';
export { default as HistoryIcon } from '../src/Assets/Icon/history.svg';
export { default as StatisticsIcon } from '../src/Assets/Icon/statistics.svg';
export { default as RightArrowIcon } from '../src/Assets/Icon/rightArrow.svg';
export {default as WifiX} from '../src/Assets/Icon/wifiX.svg';
export {default as RequestIcon} from '../src/Assets/Icon/request.svg';
export {default as UserIcon} from '../src/Assets/Icon/user.svg';
export {default as BankNoteIcon} from '../src/Assets/Icon/banknote.svg';
export {default as PencilIcon} from '../src/Assets/Icon/pencil.svg';
export {default as BackIcon} from '../src/Assets/Icon/back.svg';