export { default as DropdownIcon } from '../src/Assets/Icon/dropdown.svg';
export { default as ViewIcon } from '../src/Assets/Icon/view.svg';
export { default as DeleteIcon } from '../src/Assets/Icon/delete.svg';
export { default as CrossIcon } from '../src/Assets/Icon/cross.svg';
export { default as Cross2Icon } from '../src/Assets/Icon/cross2.svg';
export { default as CalenderIcon } from '../src/Assets/Icon/calender.svg';
export { default as SearchIcon } from '../src/Assets/Icon/search.svg';
export { default as LocationIcon } from '../src/Assets/Icon/location.svg';
export { default as HomeIcon } from '../src/Assets/Icon/home.svg';
export { default as NotificationIcon } from '../src/Assets/Icon/notification.svg';
export { default as HistoryIcon } from '../src/Assets/Icon/history.svg';
export { default as StatisticsIcon } from '../src/Assets/Icon/statistics.svg';
export { default as RightArrowIcon } from '../src/Assets/Icon/rightArrow.svg';
export {default as WifiX} from '../src/Assets/Icon/wifiX.svg';
export {default as RequestIcon} from '../src/Assets/Icon/request.svg';
export {default as UserIcon} from '../src/Assets/Icon/user.svg';
export {default as BankNoteIcon} from '../src/Assets/Icon/banknote.svg';
export {default as PencilIcon} from '../src/Assets/Icon/pencil.svg';
export {default as BackIcon} from '../src/Assets/Icon/back.svg';
export {default as CarIcon} from '../src/Assets/Icon/car.svg';
export {default as PinIcon} from '../src/Assets/Icon/pin.svg';
export {default as LeftarrowIcon} from '../src/Assets/Icon/leftarrow.svg';
export {default as EditIcon} from '../src/Assets/Icon/edit.svg';
export {default as TikIcon} from '../src/Assets/Icon/tik.svg';
export {default as CallIcon} from '../src/Assets/Icon/call.svg';
export { default as LogoutIcon } from '../src/Assets/Icon/logout.svg';
export { default as TermIcon } from '../src/Assets/Icon/term.svg';
export { default as PrivacyIcon } from '../src/Assets/Icon/privacy.svg';
export { default as ProfileIcon } from '../src/Assets/Icon/profile.svg';
export { default as SupportIcon } from '../src/Assets/Icon/support.svg';
export { default as DocIcon } from '../src/Assets/Icon/doc.svg';
export { default as ClockIcon } from '../src/Assets/Icon/clock.svg';
export { default as Notification2Icon } from '../src/Assets/Icon/notification2.svg';
export { default as WorkIcon } from '../src/Assets/Icon/work.svg';